ktor:
  development: true
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - com.crowdproj.resources.ktor.ApplicationKt.module
  urls:
    - "http://127.0.0.1:8080/"
    - "http://0.0.0.0:8080/"
    - "http://192.168.0.182:8080/"
resources:
  repository:
    test: "$DB_TYPE_TEST:inmemory"
    prod: "$DB_TYPE_PROD:psql"
    psql:
      password: postgres
      schema: resources
      url: "jdbc:postgresql://localhost:5433/resources"
      user: postgres

jwt:
  issuer: "http://localhost:8081/auth/realms/otus-marketplace"
  audience: "ad-users"
  realm: "otus-marketplace"
  clientId: "otus-marketplace-service"
  certUrl: "http://localhost:8081/auth/realms/otus-marketplace/protocol/openid-connect/certs"